services:
  api-image-reading:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apiimagereading
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - api-image-reading
    environment:
      - DATABASE_URL=postgresql://docker:docker@api-image-reading:5432/apiimagereading?schema=public
    deploy:
      resources:
        limits:
          memory: 3096M
        reservations:
          memory: 2048M