version: '3.8'

services:
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - api-image-reading
  api-image-reading:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apiimagereading